name: priceiq-daily

on:
  schedule:
    - cron: '0 6 * * *'      # daily 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: priceiq-daily
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Execute notebook
        run: |
          pip install papermill
          papermill "scrape+formula.ipynb" "docs/data/derived/run-output.ipynb"

      - name: Commit data
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add docs/data/** || true
          git add docs/index.html || true
          git commit -m "chore(data): daily notebook run" || echo "No changes"
          git push


